version: '3.8'

services:
  maimaitoolbot:
    build: .
    container_name: irika-maimaitoolbot
    restart: unless-stopped
    volumes:
      # 持久化資料庫與封面快取
      - ./apps/bot/data:/app/apps/bot/data
      # 映射設定檔
      - ./apps/bot/.env:/app/apps/bot/.env
      - ./apps/bot/cfg:/app/apps/bot/cfg
    environment:
      - NODE_ENV=production
